name: studio
channels:
  - conda-forge
  - defaults
dependencies:
  - paraview 
  - python
  - pip
  - pip:
    - PyQt5
    - matplotlib
    - scipy
    - pandas
    - simulariumio[physicell]
    - anndata
